#!/bin/sh

echo "Protection check!"

protected_branches="main dev"
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
echo "Current branch: $current_branch"
for branch in $protected_branches; do
    if [ "$branch" = "$current_branch" ]; then
        echo "Direct pushes to $branch are not allowed!"
        exit 1
    fi
done